modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="tdcaor_songs"
version="1.0.0"
displayName="The Dark Crystal: Age of Resistance Songs"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Jacob, MCreator"

[[dependencies.tdcaor_songs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



