/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package com.jmod.tdcaorsngs;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.PacketDistributor;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.entity.player.PlayerEvent;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.storage.WorldSavedData;
import net.minecraft.world.biome.Biome;
import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.player.ServerPlayerEntity;
import net.minecraft.entity.EntityType;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class TdcaorSongsModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public TdcaorSongsModElements() {
		sounds.put(new ResourceLocation("tdcaor_songs", "ost_"), new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "ost_")));
		sounds.put(new ResourceLocation("tdcaor_songs", "another_world_another_time"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "another_world_another_time")));
		sounds.put(new ResourceLocation("tdcaor_songs", "story_of_the_dark_crystal"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "story_of_the_dark_crystal")));
		sounds.put(new ResourceLocation("tdcaor_songs", "rian_and_mira_dreamfast"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "rian_and_mira_dreamfast")));
		sounds.put(new ResourceLocation("tdcaor_songs", "aughra_awakes"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "aughra_awakes")));
		sounds.put(new ResourceLocation("tdcaor_songs", "the_crystal_chamber"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "the_crystal_chamber")));
		sounds.put(new ResourceLocation("tdcaor_songs", "essence_draining"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "essence_draining")));
		sounds.put(new ResourceLocation("tdcaor_songs", "into_the_catacombs"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "into_the_catacombs")));
		sounds.put(new ResourceLocation("tdcaor_songs", "deet_enters_thra"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "deet_enters_thra")));
		sounds.put(new ResourceLocation("tdcaor_songs", "dzenpo"), new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "dzenpo")));
		sounds.put(new ResourceLocation("tdcaor_songs", "her_light_faded"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "her_light_faded")));
		sounds.put(new ResourceLocation("tdcaor_songs", "what_lies_at_the_dreams_end"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "what_lies_at_the_dreams_end")));
		sounds.put(new ResourceLocation("tdcaor_songs", "together_we_fight"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "together_we_fight")));
		sounds.put(new ResourceLocation("tdcaor_songs", "the_blue_flames_i"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "the_blue_flames_i")));
		sounds.put(new ResourceLocation("tdcaor_songs", "thra_is_calling"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "thra_is_calling")));
		sounds.put(new ResourceLocation("tdcaor_songs", "outcast"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "outcast")));
		sounds.put(new ResourceLocation("tdcaor_songs", "the_journey"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "the_journey")));
		sounds.put(new ResourceLocation("tdcaor_songs", "dreamspace"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "dreamspace")));
		sounds.put(new ResourceLocation("tdcaor_songs", "speak_for_the_dead"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "speak_for_the_dead")));
		sounds.put(new ResourceLocation("tdcaor_songs", "aughra_returns"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "aughra_returns")));
		sounds.put(new ResourceLocation("tdcaor_songs", "the_dark_crystal_age_of_hope"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "the_dark_crystal_age_of_hope")));
		sounds.put(new ResourceLocation("tdcaor_songs", "an_old_story"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "an_old_story")));
		sounds.put(new ResourceLocation("tdcaor_songs", "brea_and_the_library"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "brea_and_the_library")));
		sounds.put(new ResourceLocation("tdcaor_songs", "remember_your_oath"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "remember_your_oath")));
		sounds.put(new ResourceLocation("tdcaor_songs", "the_darkening"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "the_darkening")));
		sounds.put(new ResourceLocation("tdcaor_songs", "puppet_show"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "puppet_show")));
		sounds.put(new ResourceLocation("tdcaor_songs", "deet_in_the_woods"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "deet_in_the_woods")));
		sounds.put(new ResourceLocation("tdcaor_songs", "the_three_brothers_rise"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "the_three_brothers_rise")));
		sounds.put(new ResourceLocation("tdcaor_songs", "sisters"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "sisters")));
		sounds.put(new ResourceLocation("tdcaor_songs", "outside_podling_wayhouse"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "outside_podling_wayhouse")));
		sounds.put(new ResourceLocation("tdcaor_songs", "the_mystics"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "the_mystics")));
		sounds.put(new ResourceLocation("tdcaor_songs", "tales_from_the_sanctuary_tree"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "tales_from_the_sanctuary_tree")));
		sounds.put(new ResourceLocation("tdcaor_songs", "the_blue_flames_ii"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "the_blue_flames_ii")));
		sounds.put(new ResourceLocation("tdcaor_songs", "song_of_thra"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "song_of_thra")));
		sounds.put(new ResourceLocation("tdcaor_songs", "all-maudra"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "all-maudra")));
		sounds.put(new ResourceLocation("tdcaor_songs", "our_sister_is_gone"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "our_sister_is_gone")));
		sounds.put(new ResourceLocation("tdcaor_songs", "a_few_traitors"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "a_few_traitors")));
		sounds.put(new ResourceLocation("tdcaor_songs", "the_aureyal_the_throne_room"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "the_aureyal_the_throne_room")));
		sounds.put(new ResourceLocation("tdcaor_songs", "preperation_for_battle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "preperation_for_battle")));
		sounds.put(new ResourceLocation("tdcaor_songs", "attack_of_the_arathim"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "attack_of_the_arathim")));
		sounds.put(new ResourceLocation("tdcaor_songs", "the_seven_clans"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "the_seven_clans")));
		sounds.put(new ResourceLocation("tdcaor_songs", "a_new_crown"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "a_new_crown")));
		sounds.put(new ResourceLocation("tdcaor_songs", "tricky_chamberlain"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "tricky_chamberlain")));
		sounds.put(new ResourceLocation("tdcaor_songs", "the_skeksis_arrive"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "the_skeksis_arrive")));
		sounds.put(new ResourceLocation("tdcaor_songs", "battle_for_thra"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "battle_for_thra")));
		sounds.put(new ResourceLocation("tdcaor_songs", "the_scientist_engineers"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "the_scientist_engineers")));
		sounds.put(new ResourceLocation("tdcaor_songs", "end_credits"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "end_credits")));
		sounds.put(new ResourceLocation("tdcaor_songs", "the_hunter_the_storm"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("tdcaor_songs", "the_hunter_the_storm")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("tdcaor_songs").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == TdcaorSongsModElements.ModElement.class)
						elements.add((TdcaorSongsModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(TdcaorSongsModElements.ModElement::initElements);
		this.addNetworkMessage(TdcaorSongsModVariables.WorldSavedDataSyncMessage.class, TdcaorSongsModVariables.WorldSavedDataSyncMessage::buffer,
				TdcaorSongsModVariables.WorldSavedDataSyncMessage::new, TdcaorSongsModVariables.WorldSavedDataSyncMessage::handler);
		MinecraftForge.EVENT_BUS.register(this);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	@SubscribeEvent
	public void onPlayerLoggedIn(PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.getPlayer().world.isRemote) {
			WorldSavedData mapdata = TdcaorSongsModVariables.MapVariables.get(event.getPlayer().world);
			WorldSavedData worlddata = TdcaorSongsModVariables.WorldVariables.get(event.getPlayer().world);
			if (mapdata != null)
				TdcaorSongsMod.PACKET_HANDLER.send(PacketDistributor.PLAYER.with(() -> (ServerPlayerEntity) event.getPlayer()),
						new TdcaorSongsModVariables.WorldSavedDataSyncMessage(0, mapdata));
			if (worlddata != null)
				TdcaorSongsMod.PACKET_HANDLER.send(PacketDistributor.PLAYER.with(() -> (ServerPlayerEntity) event.getPlayer()),
						new TdcaorSongsModVariables.WorldSavedDataSyncMessage(1, worlddata));
		}
	}

	@SubscribeEvent
	public void onPlayerChangedDimension(PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.getPlayer().world.isRemote) {
			WorldSavedData worlddata = TdcaorSongsModVariables.WorldVariables.get(event.getPlayer().world);
			if (worlddata != null)
				TdcaorSongsMod.PACKET_HANDLER.send(PacketDistributor.PLAYER.with(() -> (ServerPlayerEntity) event.getPlayer()),
						new TdcaorSongsModVariables.WorldSavedDataSyncMessage(1, worlddata));
		}
	}
	private int messageID = 0;
	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		TdcaorSongsMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final TdcaorSongsModElements elements;
		protected final int sortid;
		public ModElement(TdcaorSongsModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
